### ISSUE TITLE
Create central CSS file

### ISSUE THREAD

**Issue by ThePittCrew14163** [ThePittCrew14163/thePittCrew14163.github.io#2]
Instead of writing the css code in each html file, we need to create just one css file for all of the pages. Also, the css on one page is either nonexistent or not working.

**Comment by ThePittCrew14163** [comment]
Created new css file but have yet to put anything in it.

**Comment by AndreBacic** [comment]
Also we added bootstrap and have yet to use it much

**Comment by ThePittCrew14163** [comment]
Ok we actually do have a central css file and it works so I'm closing this way obsolete issue
